name: Python package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        python-version: ['3.10'] # ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11-dev']
        windows-platform: ['Win32', 'x64']
        windows-platformtoolset: ['v140']  # all supported python versions can use this one
        exclude:
          - platform: 'ubuntu-latest'
            windows-platform: 'Win32'
          - platform: 'macos-latest'
            windows-platform: 'Win32'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install libgmp (Ubuntu)
      run: sudo apt-get install -y libgmp-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Generate Files (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        ./cddlib-makefile-gmp.ps1
        dir cddlib\\lib-src\\
        python --version
        python -c \"import struct; print(struct.calcsize('P') * 8)\"
        wget "http://mpir.org/mpir-3.0.0.zip" -outfile "mpir-3.0.0.zip"
        7z x mpir-3.0.0.zip > NUL
        msbuild mpir-3.0.0/build.vc14/lib_mpir_gc/lib_mpir_gc.vcxproj /p:Configuration=Release /p:Platform=${{ matrix.windows-platform }} /p:PlatformToolset=${{ matrix.windows-platformtoolset }} /verbosity:normal
        dir mpir-3.0.0\\lib\\${{ matrix.windows-platform }}\\Release\\"
        python -m pip install --install-option=\"--no-cython-compile\" Cython
        python -m pip install Sphinx pytest wheel twine numpy
        python setup.py build build_ext -Impir-3.0.0/lib/${{ matrix.windows-platform }}/Release/ -Lmpir-3.0.0/build.vc14/lib_mpir_gc/${{ matrix.windows-platform }}/Release/
        python setup.py bdist_wheel
        dir dist
        cd dist
        pip install --pre --no-index --find-links=. pycddlib
        cd ..
    - name: Generate Files (Non-Windows)
      if: matrix.os != 'windows-latest'
      run: |
        ./cddlib-makefile-gmp.sh
        python -m pip install --install-option="--no-cython-compile" Cython
        python -m pip install Sphinx pytest numpy
        python -m pip install .
        cd docs
        make doctest
